-- =========================================================
-- Snowflake bootstrap for portfolio ELT project
-- =========================================================

-- 1) Compute
CREATE WAREHOUSE IF NOT EXISTS PORTFOLIO_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 2) Main database
CREATE DATABASE IF NOT EXISTS ECOMMERCE_ELT;

-- 3) Schemas by layer
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_ELT.RAW;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_ELT.STAGING;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_ELT.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_ELT.MARTS;

-- 4) CSV file format for incoming files
CREATE FILE FORMAT IF NOT EXISTS ECOMMERCE_ELT.RAW.CSV_FORMAT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

-- 5) Named stage for raw files
CREATE STAGE IF NOT EXISTS ECOMMERCE_ELT.RAW.RAW_STAGE
  FILE_FORMAT = ECOMMERCE_ELT.RAW.CSV_FORMAT;

-- 6) Project role
CREATE ROLE IF NOT EXISTS PORTFOLIO_ENGINEER_ROLE;

-- 7) Grants
GRANT USAGE ON WAREHOUSE PORTFOLIO_WH TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT USAGE ON DATABASE ECOMMERCE_ELT TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_ELT
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA ECOMMERCE_ELT.RAW
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA ECOMMERCE_ELT.STAGING
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA ECOMMERCE_ELT.INTERMEDIATE
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA ECOMMERCE_ELT.MARTS
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA ECOMMERCE_ELT.RAW
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ECOMMERCE_ELT.RAW
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA ECOMMERCE_ELT.STAGING
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ECOMMERCE_ELT.STAGING
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA ECOMMERCE_ELT.INTERMEDIATE
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ECOMMERCE_ELT.INTERMEDIATE
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA ECOMMERCE_ELT.MARTS
  TO ROLE PORTFOLIO_ENGINEER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA ECOMMERCE_ELT.MARTS
  TO ROLE PORTFOLIO_ENGINEER_ROLE;